# Generated by Django 4.2.23 on 2025-07-23 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allegro_id', models.CharField(db_index=True, help_text='Unikalny ID użytkownika z Allegro', max_length=255, unique=True)),
                ('login', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Klient Allegro',
                'verbose_name_plural': 'Klienci Allegro',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_form_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('BOUGHT', 'Kupione'), ('FILLED_IN', 'Wypełniono formularz'), ('READY_FOR_PROCESSING', 'Gotowe do realizacji')], max_length=50)),
                ('allegro_updated_at', models.DateTimeField()),
                ('delivery_method_name', models.CharField(max_length=255)),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_street', models.CharField(max_length=255)),
                ('delivery_city', models.CharField(max_length=255)),
                ('delivery_post_code', models.CharField(max_length=20)),
                ('delivery_country_code', models.CharField(max_length=2)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('total_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='Klient, który złożył zamówienie', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='allegro_integration.client')),
                ('user', models.ForeignKey(help_text='Użytkownik systemowy (sprzedawca)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zamówienie Allegro',
                'verbose_name_plural': 'Zamówienia Allegro',
                'ordering': ['-allegro_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('offer_id', models.CharField(db_index=True, max_length=255)),
                ('offer_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bought_at', models.DateTimeField()),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL zdjęcia')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Sygnatura (SKU)')),
                ('offer_format', models.CharField(blank=True, choices=[('BUY_NOW', 'Kup Teraz'), ('AUCTION', 'Licytacja'), ('ADVERTISEMENT', 'Ogłoszenie')], max_length=20, null=True, verbose_name='Format oferty')),
                ('auction_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Koniec licytacji')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='allegro_integration.order')),
            ],
            options={
                'verbose_name': 'Pozycja zamówienia',
                'verbose_name_plural': 'Pozycje zamówienia',
            },
        ),
        migrations.CreateModel(
            name='AllegroProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Token dostępowy Allegro')),
                ('refresh_token', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Token odświeżający Allegro')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token wygasa o')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allegro_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
